# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
builds:
  - main: ./cmd/mcbdd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
upx:
  - enabled: true
    goos: [linux]
    compress: best
    lzma: true
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "git.techniverse.net/scriptos/mailcow-birthday-daemon:{{ .Major }}"
      - "git.techniverse.net/scriptos/mailcow-birthday-daemon:{{ .Major }}.{{ .Minor }}"
      - "git.techniverse.net/scriptos/mailcow-birthday-daemon:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "git.techniverse.net/scriptos/mailcow-birthday-daemon:latest"
